version: 2
updates:
  - package-ecosystem: npm
    directory: "/apps/web"
    schedule:
      interval: weekly
      time: "02:00"
    open-pull-requests-limit: 10
  - package-ecosystem: gomod
    directory: "/apps/server"
    schedule:
      interval: weekly
      time: "02:00"
    open-pull-requests-limit: 10
