c:
	@for file in *.c; do \
		$(CC) -Os -g3 -Wall -fsanitize=address,signed-integer-overflow -o `echo $$file | cut -d. -f1`.test $$file; \
		./`echo $$file | cut -d. -f1`.test; \
		$(RM) -rf `echo $$file | cut -d. -f1`.test *.dSYM; \
	done

cc:
	@for file in *.cc; do \
		$(CXX) -Os -g3 -fsanitize=address,signed-integer-overflow -o `echo $$file | cut -d. -f1`.test $$file; \
		./`echo $$file | cut -d. -f1`.test; \
		$(RM) -rf `echo $$file | cut -d. -f1`.test *.dSYM; \
	done

rust:
	@for file in *.rs; do \
		rustc -o `echo $$file | cut -d. -f1`.test $$file; \
		./`echo $$file | cut -d. -f1`.test; \
		$(RM) -rf `echo $$file | cut -d. -f1`.test; \
	done

golang:
	@for file in *.go; do \
		go run $$file; \
	done

python:
	@for file in *.py; do \
		python3 $$file; \
	done

node:
	@for file in *.js; do \
		node $$file; \
	done
