FROM buildpack-deps:curl

RUN mkdir -p /etc/6leetcode
COPY apps/server/wait-for-it.sh /usr/bin
COPY apps/server/config.yml /etc/6leetcode
COPY apps/server/release/6leetcode /usr/bin
COPY questions /questions

EXPOSE 4000

CMD ["6leetcode", "server"]
