version: "3.8"

services:
  6leetcode-dev:
    image: 6leetcode/6leetcode:latest
    container_name: 6leetcode-dev
    hostname: 6leetcode-dev
    build:
      context: $PWD/../..
      dockerfile: apps/server/Dockerfile.dev
    restart: always
    depends_on:
      - postgresql-dev
    ports:
      - 4000:4000
    volumes:
      - $PWD/config.yml:/etc/6leetcode/config.yml
    networks:
      - default
  postgresql-dev:
    image: docker.io/bitnami/postgresql:13-debian-10
    container_name: postgresql-dev
    hostname: postgresql-dev
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=${DATABASE_SECRET}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
