version: "3.8"

services:
  6leetcode:
    container_name: 6leetcode
    image: 6leetcode:release
    hostname: 6leetcode
    build:
      context: $PWD/../..
      dockerfile: apps/server/docker.release.Dockerfile
    restart: always
    networks:
      - default
    labels:
      - traefik.http.routers.6leetcode.rule=Host(`6leetcode${HOST_DOMAIN}`)
      - traefik.http.routers.6leetcode.entrypoints=websecure
      - traefik.http.routers.6leetcode.tls=true
      - traefik.http.routers.6leetcode.tls.certresolver=leresolver
      - traefik.http.services=6leetcode
      - traefik.http.services.6leetcode.loadbalancer.server.port=4000
networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-webproxy}
