FROM buildpack-deps:curl

RUN mkdir -p /etc/6leetcode
ADD wait-for-it.sh /usr/bin
ADD config.yml /etc/6leetcode
ADD release/6leetcode /usr/bin

EXPOSE 4000

CMD ["wait-for-it.sh", "postgresql-dev:5432", "--", "6leetcode", "server"]
