version: "3.7"

services:
  6leetcode:
    container_name: 6leetcode
    image: 6leetcode:release
    hostname: 6leetcode
    build:
      context: $PWD/../..
      dockerfile: apps/backends/docker.release.Dockerfile
    command: ["6leetcode-linux", "server"]
    restart: always
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=4000"
      - "traefik.frontend.rule=Host:6leetcode${HOST_DOMAIN}"
  6leetcode-dev:
    container_name: 6leetcode-dev
    image: 6leetcode:dev
    hostname: 6leetcode-dev
    build:
      context: $PWD/../..
      dockerfile: apps/backends/docker.dev.Dockerfile
    restart: always
    tty: true
    networks:
      - default
    volumes:
      - $PWD/../..:/root/go/src/github.com/6leetcode/6leetcode
    labels:
      - "traefik.enable=true"
      - "traefik.port=4000"
      - "traefik.frontend.rule=Host:test.6leetcode${HOST_DOMAIN}"
networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-webproxy}
