name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  leetcode-ci:
    name: leetcode-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Build server
        run: cd apps/server && make docker-build
      - name: Test code in specific image
        run: make all
