name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13", "1.14"]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Setup Go env
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.go }}
      - name: Build backend
        run: make -C apps/backends
      - name: Build the Docker image
        run: make php gcc golang java python rust node
