name: Server Build Image

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  leetcode-server-image:
    name: leetcode-server-image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Generate config files
        run: |
          cd apps/server
          if [ ! -f .env ]; then cp .env.sample .env; fi
          if [ ! -f config.yml ]; then cp config.yml.sample config.yml; fi
      - name: Docker meta
        id: docker_server_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: 6leetcode/server
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Move the questions
        run: |
          cp -r questions apps/server
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          file: apps/server/Dockerfile
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.docker_server_meta.outputs.tags }}
  leetcode-fe-image:
    name: leetcode-fe-image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Generate config files
        run: |
          cd apps/server
          if [ ! -f .env ]; then cp .env.sample .env; fi
          if [ ! -f config.yml ]; then cp config.yml.sample config.yml; fi
      - name: Docker meta
        id: docker_web_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: 6leetcode/web
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          file: apps/web/Dockerfile
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.docker_web_meta.outputs.tags }}
