name: Server Build Image

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  leetcode-image:
    name: leetcode-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Generate config files
        run: |
          cd apps/server
          if [ ! -f .env ]; then cp .env.sample .env; fi
          if [ ! -f config.yml ]; then cp config.yml.sample config.yml; fi
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 6leetcode/6leetcode
          tag_with_ref: true
          always_pull: true
          push: ${{ startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/remotes/origin/master' }}
          dockerfile: apps/server/Dockerfile
          path: .
