name: Create Pull Request

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  create-pull-request:
    runs-on: ubuntu-20.04
    env:
      Username: ${{ secrets.LEETCODE_NAME }}
      Password: ${{ secrets.LEETCODE_PASSWORD }}
      PREFIX: /usr
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Config git
        run: |
          git config user.name 'Tosone'
          git config user.email 'i@tosone.cn'
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build server
        run: sudo make install
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run executable
        run: |
          leet all
          if [ ! -z "$(git status --untracked-files=no --porcelain)" ]; then \
            git add . && \
            git commit -S -m ":robot: Generate questions"; \
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch: generate-questions
          branch-suffix: timestamp
          title: "Generate questions"
