on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate config files
        run: |
          cd apps/server
          if [ ! -f .env ]; then cp .env.sample .env; fi
          if [ ! -f config.yml ]; then cp config.yml.sample config.yml; fi
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install go-bindata
        run: go get -u -v github.com/go-bindata/go-bindata/...
      - name: Install swag
        run: go get -u -v github.com/swaggo/swag/cmd/swag
      - name: Build fontend
        run: |
          cd apps/web
          npm install -g yarn
          yarn
          yarn build
      - name: Build server
        run: |
          cd apps/server
          make
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
