name: Server Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  leetcode-server-lint:
    name: leetcode-server-lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Move the questions
        run: |
          cp -r questions apps/server
      - name: Lint code
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: apps/server
          args: -v --timeout=5m
  leetcode-server:
    name: leetcode-server
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ["1.16"]
        node: ["15"]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Generate config files
        run: |
          cd apps/server
          if [ ! -f .env ]; then cp .env.sample .env; fi
          if [ ! -f config.yml ]; then cp config.yml.sample config.yml; fi
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install swag
        run: go get -u -v github.com/swaggo/swag/cmd/swag
      - name: Move the questions
        run: |
          cp -r questions apps/server
      - name: Build server
        run: |
          cd apps/server
          make
  leetcode-fe:
    name: leetcode-fe
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ["15"]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Build fontend
        run: |
          cd apps/web
          npm install -g yarn
          yarn
          yarn build
