name: Server Build CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  leetcode-ci:
    name: leetcode-ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.15"]
        node: ["15"]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Generate config files
        run: |
          cd apps/server
          if [ ! -f .env ]; then cp .env.sample .env; fi
          if [ ! -f config.yml ]; then cp config.yml.sample config.yml; fi
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install go-bindata
        run: go get -u github.com/go-bindata/go-bindata/...
      - name: Build fontend
        run: |
          cd apps/web
          npm install -g yarn
          yarn
          yarn build
      - name: Lint code
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.28
          working-directory: apps/server
      - name: Build server
        run: |
          cd apps/server
          make
