name: Server Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  leetcode-server-lint:
    name: leetcode-server-lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Lint code
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: apps/cli
          args: -v --timeout=5m
  leetcode-server:
    name: leetcode-server
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ["1.16"]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build server
        run: |
          cd apps/cli
          make
  leetcode-fe:
    name: leetcode-fe
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ["12"]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Build fontend
        run: |
          cd apps/web
          npm install
          npm run build
